name: crypto_pulse
version: 1.0.0
config-version: 2

profile: crypto_pulse

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

clean-targets:
  - target
  - dbt_packages

models:
  crypto_pulse:
    silver:
      +schema: silver
      +materialized: table
    gold:
      +schema: gold
      +materialized: table

vars:
  tracked_coins: ["bitcoin", "ethereum", "solana"]
